CREATE TABLE THEATRE (
theaterID CHAR(5) PRIMARY KEY,
name VARCHAR(50) NOT NULL,
num_of_screen INTEGER NOT NULL,
seat_capacity INTEGER NOT NULL,
street VARCHAR(100) NOT NULL,
city VARCHAR(50) NOT NULL,
zip CHAR(10) NOT NULL,
state CHAR(2) NOT NULL
);



CREATE TABLE CUSTOMER (
customerID CHAR(10) PRIMARY KEY
23
fname VARCHAR(50) NOT NULL,
lname VARCHAR(50) NOT NULL,
cust_email VARCHAR(255) UNIQUE NOT NULL
);



CREATE TABLE EMPLOYEE (
empID CHAR(10) PRIMARY KEY,
theaterID CHAR(5) NOT NULL,
ROLE VARCHAR(50) NOT NULL,
fname VARCHAR(50) NOT NULL,
lname VARCHAR(50) NOT NULL,
emp_email VARCHAR(100) NOT NULL,
emp_phone VARCHAR(20) NOT NULL,
hire_date DATE NOT NULL,
FOREIGN KEY (theaterID) REFERENCES THEATRE (theaterID)
);



CREATE TABLE PAYROLL (
payrollID CHAR(10) PRIMARY KEY,
empID CHAR(10) NOT NULL,
pp_start DATE NOT NULL,
pp_end DATE NOT NULL,
salary CURRENCY NOT NULL,
deductions CURRENCY NOT NULL,
net_pay CURRENCY NOT NULL,
FOREIGN KEY (empID) REFERENCES EMPLOYEE (empID)
);




CREATE TABLE MEMBERSHIP (
memberID CHAR(10) PRIMARY KEY,
customerID CHAR(10) NOT NULL,
tier_lvl VARCHAR(20) NOT NULL,
points INTEGER,
join_date DATE NOT NULL,
25
exp_date DATE,
FOREIGN KEY (customerID) REFERENCES CUSTOMER (customerID)
);



CREATE TABLE CONCESSIONS (
concessionID CHAR(5) PRIMARY KEY,
theaterID CHAR(5) NOT NULL,
item_name VARCHAR(50) NOT NULL,
item_type VARCHAR(50) NOT NULL,
item_price CURRENCY NOT NULL,
item_stock INTEGER NOT NULL,
supplier VARCHAR(100) NOT NULL,
FOREIGN KEY (theaterID) REFERENCES THEATRE (theaterID)
);



CREATE TABLE MOVIE (
26
movieID CHAR(5) PRIMARY KEY,
theaterID CHAR(5) NOT NULL,
title VARCHAR(255) NOT NULL,
genre VARCHAR(50) NOT NULL,
duration INTEGER NOT NULL,
rating CHAR(5) NOT NULL,
rel_date DATE NOT NULL,
FOREIGN KEY (theaterID) REFERENCES THEATRE (theaterID)
);



CREATE TABLE RESERVATION (
resID CHAR(10) PRIMARY KEY,
memberID CHAR(10) NOT NULL,
movieID CHAR(5) NOT NULL,
theaterID CHAR(5) NOT NULL,
showtime DATETIME NOT NULL,
num_of_tickets INTEGER NOT NULL,
27
seat_num VARCHAR(5) NOT NULL,
res_date DATE NOT NULL,
pay_status VARCHAR(20) NOT NULL,
FOREIGN KEY (memberID) REFERENCES MEMBERSHIP (memberID),
FOREIGN KEY (movieID) REFERENCES MOVIE (movieID),
FOREIGN KEY (theaterID) REFERENCES THEATRE (theaterID)
);
